language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t emcooper/docker-react-example -f Dockerfile.dev .

script:
  - docker run emcooper/docker-react-example npm run test -- --coverage