language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t emcooper/docker-react-example -f Dockerfile.dev .

script:
  - docker run -e CI=true emcooper/docker-react-example npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-example"
  env: "DockerReactExample-env"
  bucket_name: "elasticbeanstalk-us-east-2-678805402556"
  bucket_path: "docker-react-example"
  on: 
    branch: master

